export const WIDGET_REGISTRY = {
  'revenue-velocity': {
    id: 'revenue-velocity',
    name: 'Revenue Velocity',
    description: 'Daily revenue last 30 days with target line',
    category: 'Revenue',
    defaultSize: { w: 8, h: 4 },
    minSize: { w: 4, h: 3 },
  },
  'quote-funnel': {
    id: 'quote-funnel',
    name: 'Quote Funnel',
    description: 'Created → Sent → Viewed → Accepted → Paid',
    category: 'Conversion',
    defaultSize: { w: 12, h: 3 },
    minSize: { w: 6, h: 3 },
  },
  'cash-collected-today': {
    id: 'cash-collected-today',
    name: 'Cash Collected Today',
    description: 'Today\'s cash vs yesterday and 7-day avg',
    category: 'Revenue',
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
  },
  'leads-to-close': {
    id: 'leads-to-close',
    name: 'Leads to Close Rate',
    description: '% of quotes sent that become paid',
    category: 'Conversion',
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
  },
  'average-ticket': {
    id: 'average-ticket',
    name: 'Average Ticket Value',
    description: 'Avg job value with sparkline trend',
    category: 'Revenue',
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
  },
  'revenue-by-aircraft': {
    id: 'revenue-by-aircraft',
    name: 'Revenue per Aircraft Type',
    description: 'Horizontal bar chart by aircraft type',
    category: 'Revenue',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
  },
  'busiest-days-heatmap': {
    id: 'busiest-days-heatmap',
    name: 'Busiest Days Heatmap',
    description: 'Day-of-week heatmap with gold intensity',
    category: 'Operations',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 4 },
  },
  'top-services-margin': {
    id: 'top-services-margin',
    name: 'Top Services by Revenue',
    description: 'Most profitable services ranked',
    category: 'Revenue',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
  },
  'customer-ltv': {
    id: 'customer-ltv',
    name: 'Customer LTV',
    description: 'Top 10 customers by lifetime value',
    category: 'Customers',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
  },
  'churn-risk': {
    id: 'churn-risk',
    name: 'Churn Risk',
    description: 'Customers not booked in 60/90/120 days',
    category: 'Customers',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
  },
  'mrr-trend': {
    id: 'mrr-trend',
    name: 'Monthly Revenue Trend',
    description: 'Line chart of monthly revenue',
    category: 'Revenue',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 6, h: 3 },
  },
};

export const DEFAULT_ACTIVE_WIDGETS = [
  'revenue-velocity', 'cash-collected-today', 'quote-funnel',
  'leads-to-close', 'average-ticket', 'revenue-by-aircraft',
  'busiest-days-heatmap', 'top-services-margin',
  'customer-ltv', 'churn-risk', 'mrr-trend',
];

export const DEFAULT_LAYOUTS = {
  lg: [
    { i: 'revenue-velocity',     x: 0, y: 0,  w: 8,  h: 4 },
    { i: 'cash-collected-today',  x: 8, y: 0,  w: 4,  h: 4 },
    { i: 'quote-funnel',          x: 0, y: 4,  w: 12, h: 3 },
    { i: 'leads-to-close',        x: 0, y: 7,  w: 3,  h: 3 },
    { i: 'average-ticket',        x: 3, y: 7,  w: 3,  h: 3 },
    { i: 'revenue-by-aircraft',   x: 6, y: 7,  w: 6,  h: 4 },
    { i: 'busiest-days-heatmap',  x: 0, y: 11, w: 6,  h: 5 },
    { i: 'top-services-margin',   x: 6, y: 11, w: 6,  h: 4 },
    { i: 'customer-ltv',          x: 0, y: 16, w: 6,  h: 5 },
    { i: 'churn-risk',            x: 6, y: 16, w: 6,  h: 5 },
    { i: 'mrr-trend',             x: 0, y: 21, w: 12, h: 4 },
  ],
  md: [
    { i: 'revenue-velocity',     x: 0, y: 0,  w: 6, h: 4 },
    { i: 'cash-collected-today',  x: 0, y: 4,  w: 6, h: 3 },
    { i: 'quote-funnel',          x: 0, y: 7,  w: 6, h: 3 },
    { i: 'leads-to-close',        x: 0, y: 10, w: 3, h: 3 },
    { i: 'average-ticket',        x: 3, y: 10, w: 3, h: 3 },
    { i: 'revenue-by-aircraft',   x: 0, y: 13, w: 6, h: 4 },
    { i: 'busiest-days-heatmap',  x: 0, y: 17, w: 6, h: 5 },
    { i: 'top-services-margin',   x: 0, y: 22, w: 6, h: 4 },
    { i: 'customer-ltv',          x: 0, y: 26, w: 6, h: 5 },
    { i: 'churn-risk',            x: 0, y: 31, w: 6, h: 5 },
    { i: 'mrr-trend',             x: 0, y: 36, w: 6, h: 4 },
  ],
  sm: [
    { i: 'revenue-velocity',     x: 0, y: 0,  w: 1, h: 4 },
    { i: 'cash-collected-today',  x: 0, y: 4,  w: 1, h: 3 },
    { i: 'quote-funnel',          x: 0, y: 7,  w: 1, h: 4 },
    { i: 'leads-to-close',        x: 0, y: 11, w: 1, h: 3 },
    { i: 'average-ticket',        x: 0, y: 14, w: 1, h: 3 },
    { i: 'revenue-by-aircraft',   x: 0, y: 17, w: 1, h: 4 },
    { i: 'busiest-days-heatmap',  x: 0, y: 21, w: 1, h: 5 },
    { i: 'top-services-margin',   x: 0, y: 26, w: 1, h: 4 },
    { i: 'customer-ltv',          x: 0, y: 30, w: 1, h: 5 },
    { i: 'churn-risk',            x: 0, y: 35, w: 1, h: 5 },
    { i: 'mrr-trend',             x: 0, y: 40, w: 1, h: 4 },
  ],
};

export const CHART_THEME = {
  gold: '#C9A84C',
  goldDim: '#A68A3E',
  surface: '#1A2236',
  charcoal: '#0F1117',
  textPrimary: '#F5F5F5',
  textSecondary: '#8A9BB0',
  success: '#2ECC71',
  danger: '#E74C3C',
  warning: '#d97706',
  gridColor: 'rgba(138, 155, 176, 0.1)',
  tooltipBg: '#1A2236',
  tooltipBorder: '#2A3A50',
};
