export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/settings/',
          '/crew/',
          '/onboarding/',
          '/customer/',
          '/vendor/',
          '/portal/',
          '/quotes/',
          '/invoices/',
          '/jobs/',
          '/calendar/',
          '/notifications/',
          '/documents/',
          '/equipment/',
          '/products/',
          '/marketing/',
          '/analytics/',
          '/profitability/',
          '/reports/',
          '/referrals/',
          '/rewards/',
          '/roi/',
          '/team/',
          '/time-log/',
          '/scheduled-quotes/',
          '/recurring/',
          '/growth/',
          '/shop/',
          '/inventory/',
        ],
      },
    ],
    sitemap: 'https://crm.shinyjets.com/sitemap.xml',
  };
}
