// Comprehensive aircraft database - 220+ civilian + military aircraft
// Hours are default estimates for detailing (exterior and interior)
// Surface area in sq ft estimated from dimensions

export const AIRCRAFT_DATA = [
  // ============ PISTON / SINGLE ENGINE ============
  { manufacturer: 'Cessna', model: '150', category: 'piston', seats: 2, wingspan_ft: 33, length_ft: 24, height_ft: 8.5, surface_area_sqft: 180, exterior_hours: 1.5, interior_hours: 0.75 },
  { manufacturer: 'Cessna', model: '152', category: 'piston', seats: 2, wingspan_ft: 33, length_ft: 24, height_ft: 8.5, surface_area_sqft: 185, exterior_hours: 1.5, interior_hours: 0.75 },
  { manufacturer: 'Cessna', model: '172 Skyhawk', category: 'piston', seats: 4, wingspan_ft: 36, length_ft: 27, height_ft: 8.8, surface_area_sqft: 220, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cessna', model: '177 Cardinal', category: 'piston', seats: 4, wingspan_ft: 35.5, length_ft: 27, height_ft: 8.7, surface_area_sqft: 215, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cessna', model: '182 Skylane', category: 'piston', seats: 4, wingspan_ft: 36, length_ft: 29, height_ft: 9.2, surface_area_sqft: 240, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cessna', model: '206 Stationair', category: 'piston', seats: 6, wingspan_ft: 36, length_ft: 28, height_ft: 9.3, surface_area_sqft: 260, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Cessna', model: '210 Centurion', category: 'piston', seats: 6, wingspan_ft: 36.8, length_ft: 28.3, height_ft: 9.8, surface_area_sqft: 270, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Cessna', model: 'TTx', category: 'piston', seats: 4, wingspan_ft: 36, length_ft: 25.2, height_ft: 9, surface_area_sqft: 230, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Piper', model: 'Cherokee 140', category: 'piston', seats: 4, wingspan_ft: 30, length_ft: 23.3, height_ft: 7.3, surface_area_sqft: 190, exterior_hours: 1.75, interior_hours: 0.75 },
  { manufacturer: 'Piper', model: 'Warrior II (PA-28-161)', category: 'piston', seats: 4, wingspan_ft: 35, length_ft: 24, height_ft: 7.3, surface_area_sqft: 210, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Piper', model: 'Archer III (PA-28-181)', category: 'piston', seats: 4, wingspan_ft: 35, length_ft: 24, height_ft: 7.3, surface_area_sqft: 215, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Piper', model: 'Arrow (PA-28R-201)', category: 'piston', seats: 4, wingspan_ft: 35.4, length_ft: 24.7, height_ft: 8, surface_area_sqft: 225, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Piper', model: 'Saratoga (PA-32)', category: 'piston', seats: 6, wingspan_ft: 36.2, length_ft: 27.7, height_ft: 8.2, surface_area_sqft: 260, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Piper', model: 'Lance (PA-32R-300)', category: 'piston', seats: 6, wingspan_ft: 32.8, length_ft: 27.7, height_ft: 8.9, surface_area_sqft: 255, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Piper', model: 'Comanche 250', category: 'piston', seats: 4, wingspan_ft: 36, length_ft: 25, height_ft: 7.3, surface_area_sqft: 220, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Piper', model: 'Malibu (PA-46-310P)', category: 'piston', seats: 6, wingspan_ft: 43, length_ft: 28.5, height_ft: 11.3, surface_area_sqft: 310, exterior_hours: 2.5, interior_hours: 1.5 },
  { manufacturer: 'Piper', model: 'Matrix (PA-46R-350T)', category: 'piston', seats: 6, wingspan_ft: 43, length_ft: 29, height_ft: 11.3, surface_area_sqft: 315, exterior_hours: 2.5, interior_hours: 1.5 },
  { manufacturer: 'Piper', model: 'M350', category: 'piston', seats: 6, wingspan_ft: 43, length_ft: 29, height_ft: 11.3, surface_area_sqft: 320, exterior_hours: 2.75, interior_hours: 1.5 },
  { manufacturer: 'Piper', model: 'Cub (J-3)', category: 'piston', seats: 2, wingspan_ft: 35.2, length_ft: 22.5, height_ft: 6.8, surface_area_sqft: 170, exterior_hours: 1.5, interior_hours: 0.5 },
  { manufacturer: 'Piper', model: 'Super Cub (PA-18)', category: 'piston', seats: 2, wingspan_ft: 35.2, length_ft: 22.7, height_ft: 6.8, surface_area_sqft: 175, exterior_hours: 1.5, interior_hours: 0.5 },
  { manufacturer: 'Beechcraft', model: 'Bonanza A36', category: 'piston', seats: 6, wingspan_ft: 33.5, length_ft: 27.5, height_ft: 8.6, surface_area_sqft: 250, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Beechcraft', model: 'Bonanza G36', category: 'piston', seats: 6, wingspan_ft: 33.5, length_ft: 27.5, height_ft: 8.6, surface_area_sqft: 255, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Beechcraft', model: 'Bonanza V35', category: 'piston', seats: 4, wingspan_ft: 33.5, length_ft: 26.4, height_ft: 6.6, surface_area_sqft: 235, exterior_hours: 2.25, interior_hours: 1 },
  { manufacturer: 'Beechcraft', model: 'Baron 58', category: 'piston', seats: 6, wingspan_ft: 37.8, length_ft: 29.8, height_ft: 9.7, surface_area_sqft: 300, exterior_hours: 3, interior_hours: 1.5 },
  { manufacturer: 'Beechcraft', model: 'Baron G58', category: 'piston', seats: 6, wingspan_ft: 37.8, length_ft: 29.8, height_ft: 9.7, surface_area_sqft: 305, exterior_hours: 3, interior_hours: 1.5 },
  { manufacturer: 'Mooney', model: 'M20J (201)', category: 'piston', seats: 4, wingspan_ft: 36.1, length_ft: 24.8, height_ft: 8.3, surface_area_sqft: 210, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Mooney', model: 'M20K (231)', category: 'piston', seats: 4, wingspan_ft: 36.1, length_ft: 25, height_ft: 8.3, surface_area_sqft: 215, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Mooney', model: 'M20R Ovation', category: 'piston', seats: 4, wingspan_ft: 36.1, length_ft: 26.8, height_ft: 8.3, surface_area_sqft: 225, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Mooney', model: 'M20TN Acclaim', category: 'piston', seats: 4, wingspan_ft: 36.1, length_ft: 27.7, height_ft: 8.3, surface_area_sqft: 230, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cirrus', model: 'SR20', category: 'piston', seats: 4, wingspan_ft: 38.3, length_ft: 26, height_ft: 8.9, surface_area_sqft: 235, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cirrus', model: 'SR22', category: 'piston', seats: 4, wingspan_ft: 38.3, length_ft: 26, height_ft: 8.9, surface_area_sqft: 240, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Cirrus', model: 'SR22T', category: 'piston', seats: 4, wingspan_ft: 38.3, length_ft: 26, height_ft: 8.9, surface_area_sqft: 240, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Diamond', model: 'DA40', category: 'piston', seats: 4, wingspan_ft: 39.2, length_ft: 26.3, height_ft: 6.6, surface_area_sqft: 220, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Diamond', model: 'DA42 Twin Star', category: 'piston', seats: 4, wingspan_ft: 44.4, length_ft: 28.3, height_ft: 8.5, surface_area_sqft: 280, exterior_hours: 2.5, interior_hours: 1 },
  { manufacturer: 'Diamond', model: 'DA62', category: 'piston', seats: 7, wingspan_ft: 47.9, length_ft: 30.1, height_ft: 8.7, surface_area_sqft: 310, exterior_hours: 3, interior_hours: 1.5 },
  { manufacturer: 'Grumman', model: 'AA-5 Tiger', category: 'piston', seats: 4, wingspan_ft: 31.5, length_ft: 22, height_ft: 8, surface_area_sqft: 185, exterior_hours: 1.75, interior_hours: 0.75 },
  { manufacturer: 'Maule', model: 'M-7-235C', category: 'piston', seats: 4, wingspan_ft: 33.8, length_ft: 23.5, height_ft: 6.3, surface_area_sqft: 195, exterior_hours: 1.75, interior_hours: 0.75 },
  { manufacturer: 'American Champion', model: 'Citabria', category: 'piston', seats: 2, wingspan_ft: 33.4, length_ft: 22.6, height_ft: 7.7, surface_area_sqft: 175, exterior_hours: 1.5, interior_hours: 0.5 },
  { manufacturer: 'CubCrafters', model: 'XCub', category: 'piston', seats: 2, wingspan_ft: 34.8, length_ft: 23.3, height_ft: 7.1, surface_area_sqft: 185, exterior_hours: 1.5, interior_hours: 0.5 },
  { manufacturer: 'Vans', model: 'RV-10', category: 'piston', seats: 4, wingspan_ft: 32, length_ft: 25, height_ft: 8, surface_area_sqft: 200, exterior_hours: 1.75, interior_hours: 0.75 },

  // ============ TURBOPROPS ============
  { manufacturer: 'Beechcraft', model: 'King Air 90', category: 'turboprop', seats: 8, wingspan_ft: 50.3, length_ft: 35.5, height_ft: 14.3, surface_area_sqft: 480, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Beechcraft', model: 'King Air 200', category: 'turboprop', seats: 9, wingspan_ft: 54.5, length_ft: 43.8, height_ft: 15, surface_area_sqft: 580, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Beechcraft', model: 'King Air 250', category: 'turboprop', seats: 9, wingspan_ft: 54.5, length_ft: 43.8, height_ft: 15, surface_area_sqft: 590, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Beechcraft', model: 'King Air 350', category: 'turboprop', seats: 11, wingspan_ft: 57.9, length_ft: 46.7, height_ft: 14.3, surface_area_sqft: 650, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Beechcraft', model: 'King Air 350i', category: 'turboprop', seats: 11, wingspan_ft: 57.9, length_ft: 46.7, height_ft: 14.3, surface_area_sqft: 650, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Beechcraft', model: 'King Air 360', category: 'turboprop', seats: 11, wingspan_ft: 57.9, length_ft: 46.7, height_ft: 14.3, surface_area_sqft: 655, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Pilatus', model: 'PC-12', category: 'turboprop', seats: 9, wingspan_ft: 53.3, length_ft: 47.3, height_ft: 14, surface_area_sqft: 550, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Pilatus', model: 'PC-12 NGX', category: 'turboprop', seats: 10, wingspan_ft: 53.3, length_ft: 47.3, height_ft: 14, surface_area_sqft: 555, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Daher', model: 'TBM 700', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 34.9, height_ft: 14.3, surface_area_sqft: 380, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'TBM 850', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 34.9, height_ft: 14.3, surface_area_sqft: 385, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'TBM 900', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 34.9, height_ft: 14.3, surface_area_sqft: 385, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'TBM 910', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 35.1, height_ft: 14.3, surface_area_sqft: 390, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'TBM 930', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 35.1, height_ft: 14.3, surface_area_sqft: 390, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'TBM 960', category: 'turboprop', seats: 6, wingspan_ft: 42.1, length_ft: 35.1, height_ft: 14.3, surface_area_sqft: 390, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Daher', model: 'Kodiak 100', category: 'turboprop', seats: 10, wingspan_ft: 45, length_ft: 34.2, height_ft: 15.3, surface_area_sqft: 420, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Piper', model: 'Meridian (M500)', category: 'turboprop', seats: 6, wingspan_ft: 43, length_ft: 29.6, height_ft: 11.3, surface_area_sqft: 330, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Piper', model: 'M600/SLS', category: 'turboprop', seats: 6, wingspan_ft: 43.2, length_ft: 29.8, height_ft: 11.3, surface_area_sqft: 340, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Cessna', model: '208 Caravan', category: 'turboprop', seats: 14, wingspan_ft: 52.1, length_ft: 37.7, height_ft: 14.9, surface_area_sqft: 500, exterior_hours: 4, interior_hours: 3 },
  { manufacturer: 'Cessna', model: '208B Grand Caravan', category: 'turboprop', seats: 14, wingspan_ft: 52.1, length_ft: 41.6, height_ft: 14.9, surface_area_sqft: 540, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Epic', model: 'E1000 GX', category: 'turboprop', seats: 6, wingspan_ft: 43, length_ft: 36, height_ft: 11, surface_area_sqft: 380, exterior_hours: 3, interior_hours: 2 },
  { manufacturer: 'Piaggio', model: 'P.180 Avanti EVO', category: 'turboprop', seats: 9, wingspan_ft: 46, length_ft: 47.3, height_ft: 13, surface_area_sqft: 520, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'ATR', model: 'ATR 42-600', category: 'turboprop', seats: 48, wingspan_ft: 80.6, length_ft: 74.4, height_ft: 24.9, surface_area_sqft: 1400, exterior_hours: 10, interior_hours: 8 },
  { manufacturer: 'ATR', model: 'ATR 72-600', category: 'turboprop', seats: 72, wingspan_ft: 88.7, length_ft: 89.1, height_ft: 25.1, surface_area_sqft: 1700, exterior_hours: 12, interior_hours: 10 },
  { manufacturer: 'De Havilland', model: 'DHC-6 Twin Otter', category: 'turboprop', seats: 20, wingspan_ft: 65, length_ft: 51.8, height_ft: 19.5, surface_area_sqft: 750, exterior_hours: 6, interior_hours: 4 },

  // ============ LIGHT JETS ============
  { manufacturer: 'Cessna', model: 'Citation Mustang', category: 'light_jet', seats: 5, wingspan_ft: 43.2, length_ft: 40.6, height_ft: 13.5, surface_area_sqft: 450, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Cessna', model: 'Citation M2', category: 'light_jet', seats: 7, wingspan_ft: 47.3, length_ft: 42.6, height_ft: 13.9, surface_area_sqft: 490, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Cessna', model: 'Citation M2 Gen2', category: 'light_jet', seats: 7, wingspan_ft: 47.3, length_ft: 42.6, height_ft: 13.9, surface_area_sqft: 495, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Cessna', model: 'Citation CJ1', category: 'light_jet', seats: 6, wingspan_ft: 46.4, length_ft: 42.6, height_ft: 13.9, surface_area_sqft: 480, exterior_hours: 3.75, interior_hours: 2.25 },
  { manufacturer: 'Cessna', model: 'Citation CJ2', category: 'light_jet', seats: 8, wingspan_ft: 49.2, length_ft: 47.2, height_ft: 14, surface_area_sqft: 530, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Cessna', model: 'Citation CJ3', category: 'light_jet', seats: 9, wingspan_ft: 53.3, length_ft: 51.2, height_ft: 15.2, surface_area_sqft: 600, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Cessna', model: 'Citation CJ3+', category: 'light_jet', seats: 9, wingspan_ft: 53.3, length_ft: 51.3, height_ft: 15.2, surface_area_sqft: 605, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Cessna', model: 'Citation CJ4', category: 'light_jet', seats: 10, wingspan_ft: 50.8, length_ft: 53.3, height_ft: 15.4, surface_area_sqft: 620, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Cessna', model: 'Citation CJ4 Gen2', category: 'light_jet', seats: 10, wingspan_ft: 50.8, length_ft: 53.3, height_ft: 15.4, surface_area_sqft: 625, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Embraer', model: 'Phenom 100', category: 'light_jet', seats: 6, wingspan_ft: 40.4, length_ft: 42.1, height_ft: 14.3, surface_area_sqft: 420, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Embraer', model: 'Phenom 100EV', category: 'light_jet', seats: 6, wingspan_ft: 40.4, length_ft: 42.1, height_ft: 14.3, surface_area_sqft: 425, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Embraer', model: 'Phenom 300', category: 'light_jet', seats: 10, wingspan_ft: 52.2, length_ft: 51.2, height_ft: 16.8, surface_area_sqft: 600, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Embraer', model: 'Phenom 300E', category: 'light_jet', seats: 10, wingspan_ft: 52.2, length_ft: 51.2, height_ft: 16.8, surface_area_sqft: 605, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Honda', model: 'HondaJet', category: 'light_jet', seats: 6, wingspan_ft: 39.8, length_ft: 42.6, height_ft: 14.9, surface_area_sqft: 410, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Honda', model: 'HondaJet Elite', category: 'light_jet', seats: 7, wingspan_ft: 39.8, length_ft: 43.1, height_ft: 14.9, surface_area_sqft: 415, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Honda', model: 'HondaJet Elite S', category: 'light_jet', seats: 7, wingspan_ft: 39.8, length_ft: 43.1, height_ft: 14.9, surface_area_sqft: 420, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Cirrus', model: 'Vision Jet SF50', category: 'light_jet', seats: 7, wingspan_ft: 38.7, length_ft: 30.7, height_ft: 10.9, surface_area_sqft: 340, exterior_hours: 3, interior_hours: 1.75 },
  { manufacturer: 'Eclipse', model: '500', category: 'light_jet', seats: 5, wingspan_ft: 37.5, length_ft: 33.5, height_ft: 11, surface_area_sqft: 320, exterior_hours: 2.75, interior_hours: 1.5 },
  { manufacturer: 'Eclipse', model: '550', category: 'light_jet', seats: 5, wingspan_ft: 37.5, length_ft: 33.5, height_ft: 11, surface_area_sqft: 325, exterior_hours: 2.75, interior_hours: 1.5 },
  { manufacturer: 'Nextant', model: '400XTi', category: 'light_jet', seats: 8, wingspan_ft: 43.5, length_ft: 48.4, height_ft: 13.9, surface_area_sqft: 510, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Pilatus', model: 'PC-24', category: 'light_jet', seats: 10, wingspan_ft: 55.8, length_ft: 55.5, height_ft: 17.3, surface_area_sqft: 680, exterior_hours: 5, interior_hours: 3.5 },
  { manufacturer: 'SyberJet', model: 'SJ30', category: 'light_jet', seats: 6, wingspan_ft: 38.7, length_ft: 46.1, height_ft: 14.2, surface_area_sqft: 430, exterior_hours: 3.5, interior_hours: 2 },

  // ============ MIDSIZE JETS ============
  { manufacturer: 'Cessna', model: 'Citation Excel/XLS', category: 'midsize_jet', seats: 10, wingspan_ft: 56.3, length_ft: 52.5, height_ft: 17.2, surface_area_sqft: 700, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Cessna', model: 'Citation XLS+', category: 'midsize_jet', seats: 10, wingspan_ft: 56.3, length_ft: 52.5, height_ft: 17.2, surface_area_sqft: 710, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Cessna', model: 'Citation XLS Gen2', category: 'midsize_jet', seats: 10, wingspan_ft: 56.3, length_ft: 52.5, height_ft: 17.2, surface_area_sqft: 715, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Cessna', model: 'Citation Encore', category: 'midsize_jet', seats: 9, wingspan_ft: 53.4, length_ft: 48.9, height_ft: 15, surface_area_sqft: 620, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Cessna', model: 'Citation Bravo', category: 'midsize_jet', seats: 8, wingspan_ft: 52.2, length_ft: 47.2, height_ft: 15, surface_area_sqft: 600, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Cessna', model: 'Citation V Ultra', category: 'midsize_jet', seats: 8, wingspan_ft: 52.2, length_ft: 48.9, height_ft: 15, surface_area_sqft: 610, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Hawker', model: '400XP', category: 'midsize_jet', seats: 8, wingspan_ft: 43.5, length_ft: 48.4, height_ft: 13.9, surface_area_sqft: 510, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Hawker', model: '800XP', category: 'midsize_jet', seats: 9, wingspan_ft: 51.4, length_ft: 51.2, height_ft: 18, surface_area_sqft: 640, exterior_hours: 5, interior_hours: 3.5 },
  { manufacturer: 'Hawker', model: '850XP', category: 'midsize_jet', seats: 9, wingspan_ft: 54.3, length_ft: 51.2, height_ft: 18, surface_area_sqft: 660, exterior_hours: 5.25, interior_hours: 3.5 },
  { manufacturer: 'Hawker', model: '900XP', category: 'midsize_jet', seats: 9, wingspan_ft: 54.3, length_ft: 53.2, height_ft: 18, surface_area_sqft: 680, exterior_hours: 5.5, interior_hours: 3.5 },
  { manufacturer: 'Hawker', model: '4000', category: 'midsize_jet', seats: 10, wingspan_ft: 61.8, length_ft: 69.5, height_ft: 18.8, surface_area_sqft: 900, exterior_hours: 7, interior_hours: 4.5 },
  { manufacturer: 'Learjet', model: '40', category: 'midsize_jet', seats: 8, wingspan_ft: 47.9, length_ft: 55.6, height_ft: 14.1, surface_area_sqft: 570, exterior_hours: 4.5, interior_hours: 2.75 },
  { manufacturer: 'Learjet', model: '45', category: 'midsize_jet', seats: 9, wingspan_ft: 47.9, length_ft: 58, height_ft: 14.1, surface_area_sqft: 590, exterior_hours: 4.75, interior_hours: 3 },
  { manufacturer: 'Learjet', model: '45XR', category: 'midsize_jet', seats: 9, wingspan_ft: 47.9, length_ft: 58, height_ft: 14.1, surface_area_sqft: 595, exterior_hours: 4.75, interior_hours: 3 },
  { manufacturer: 'Learjet', model: '60', category: 'midsize_jet', seats: 10, wingspan_ft: 43.8, length_ft: 58.7, height_ft: 14.5, surface_area_sqft: 600, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Learjet', model: '60XR', category: 'midsize_jet', seats: 10, wingspan_ft: 43.8, length_ft: 58.7, height_ft: 14.5, surface_area_sqft: 605, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Learjet', model: '70', category: 'midsize_jet', seats: 9, wingspan_ft: 48.1, length_ft: 55.6, height_ft: 14.1, surface_area_sqft: 580, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Learjet', model: '75 Liberty', category: 'midsize_jet', seats: 9, wingspan_ft: 50.9, length_ft: 58, height_ft: 14.1, surface_area_sqft: 620, exterior_hours: 5, interior_hours: 3 },

  // ============ SUPER MIDSIZE JETS ============
  { manufacturer: 'Cessna', model: 'Citation Sovereign', category: 'super_midsize_jet', seats: 12, wingspan_ft: 63.5, length_ft: 63.5, height_ft: 20, surface_area_sqft: 850, exterior_hours: 6.5, interior_hours: 4.5 },
  { manufacturer: 'Cessna', model: 'Citation Sovereign+', category: 'super_midsize_jet', seats: 12, wingspan_ft: 63.5, length_ft: 63.5, height_ft: 20, surface_area_sqft: 855, exterior_hours: 6.5, interior_hours: 4.5 },
  { manufacturer: 'Cessna', model: 'Citation Latitude', category: 'super_midsize_jet', seats: 9, wingspan_ft: 72.3, length_ft: 62.2, height_ft: 20.9, surface_area_sqft: 880, exterior_hours: 7, interior_hours: 4.5 },
  { manufacturer: 'Cessna', model: 'Citation Longitude', category: 'super_midsize_jet', seats: 12, wingspan_ft: 68, length_ft: 73.2, height_ft: 19.8, surface_area_sqft: 980, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Cessna', model: 'Citation X', category: 'super_midsize_jet', seats: 12, wingspan_ft: 63.5, length_ft: 72.3, height_ft: 19, surface_area_sqft: 950, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Cessna', model: 'Citation X+', category: 'super_midsize_jet', seats: 12, wingspan_ft: 63.5, length_ft: 73.4, height_ft: 19, surface_area_sqft: 960, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Challenger 300', category: 'super_midsize_jet', seats: 10, wingspan_ft: 63.8, length_ft: 68.7, height_ft: 20.3, surface_area_sqft: 920, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Challenger 350', category: 'super_midsize_jet', seats: 10, wingspan_ft: 69, length_ft: 68.7, height_ft: 20.3, surface_area_sqft: 950, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Challenger 3500', category: 'super_midsize_jet', seats: 10, wingspan_ft: 69, length_ft: 68.7, height_ft: 20.3, surface_area_sqft: 955, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Gulfstream', model: 'G280', category: 'super_midsize_jet', seats: 10, wingspan_ft: 63, length_ft: 66.8, height_ft: 21, surface_area_sqft: 900, exterior_hours: 7, interior_hours: 4.5 },
  { manufacturer: 'Embraer', model: 'Legacy 450', category: 'super_midsize_jet', seats: 9, wingspan_ft: 66.4, length_ft: 64.2, height_ft: 20.8, surface_area_sqft: 860, exterior_hours: 6.5, interior_hours: 4.5 },
  { manufacturer: 'Embraer', model: 'Legacy 500', category: 'super_midsize_jet', seats: 12, wingspan_ft: 66.4, length_ft: 68, height_ft: 20.8, surface_area_sqft: 900, exterior_hours: 7, interior_hours: 4.5 },
  { manufacturer: 'Embraer', model: 'Praetor 500', category: 'super_midsize_jet', seats: 9, wingspan_ft: 69.5, length_ft: 64.2, height_ft: 20.8, surface_area_sqft: 880, exterior_hours: 7, interior_hours: 4.5 },
  { manufacturer: 'Embraer', model: 'Praetor 600', category: 'super_midsize_jet', seats: 12, wingspan_ft: 69.5, length_ft: 68, height_ft: 20.8, surface_area_sqft: 920, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Dassault', model: 'Falcon 2000S', category: 'super_midsize_jet', seats: 10, wingspan_ft: 70.2, length_ft: 66.3, height_ft: 23, surface_area_sqft: 940, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Dassault', model: 'Falcon 2000LXS', category: 'super_midsize_jet', seats: 10, wingspan_ft: 70.2, length_ft: 66.7, height_ft: 23, surface_area_sqft: 950, exterior_hours: 7, interior_hours: 5 },

  // ============ LARGE / HEAVY JETS ============
  { manufacturer: 'Gulfstream', model: 'GIV-SP', category: 'large_jet', seats: 14, wingspan_ft: 77.8, length_ft: 88.3, height_ft: 24.4, surface_area_sqft: 1350, exterior_hours: 10, interior_hours: 7 },
  { manufacturer: 'Gulfstream', model: 'GV', category: 'large_jet', seats: 16, wingspan_ft: 93.5, length_ft: 96.4, height_ft: 25.8, surface_area_sqft: 1600, exterior_hours: 12, interior_hours: 8 },
  { manufacturer: 'Gulfstream', model: 'G450', category: 'large_jet', seats: 14, wingspan_ft: 77.8, length_ft: 89.3, height_ft: 25.8, surface_area_sqft: 1400, exterior_hours: 10, interior_hours: 7 },
  { manufacturer: 'Gulfstream', model: 'G500', category: 'large_jet', seats: 19, wingspan_ft: 87, length_ft: 91.2, height_ft: 25.4, surface_area_sqft: 1500, exterior_hours: 11, interior_hours: 8 },
  { manufacturer: 'Gulfstream', model: 'G550', category: 'large_jet', seats: 16, wingspan_ft: 93.5, length_ft: 96.4, height_ft: 25.8, surface_area_sqft: 1650, exterior_hours: 12, interior_hours: 8 },
  { manufacturer: 'Gulfstream', model: 'G600', category: 'large_jet', seats: 19, wingspan_ft: 94.2, length_ft: 96.1, height_ft: 25.4, surface_area_sqft: 1680, exterior_hours: 12, interior_hours: 8.5 },
  { manufacturer: 'Gulfstream', model: 'G650', category: 'large_jet', seats: 19, wingspan_ft: 99.6, length_ft: 99.8, height_ft: 25.8, surface_area_sqft: 1800, exterior_hours: 14, interior_hours: 9 },
  { manufacturer: 'Gulfstream', model: 'G650ER', category: 'large_jet', seats: 19, wingspan_ft: 99.6, length_ft: 99.8, height_ft: 25.8, surface_area_sqft: 1810, exterior_hours: 14, interior_hours: 9 },
  { manufacturer: 'Gulfstream', model: 'G700', category: 'large_jet', seats: 19, wingspan_ft: 103, length_ft: 109.8, height_ft: 25.3, surface_area_sqft: 2000, exterior_hours: 16, interior_hours: 10 },
  { manufacturer: 'Gulfstream', model: 'G800', category: 'large_jet', seats: 19, wingspan_ft: 103, length_ft: 109.8, height_ft: 25.3, surface_area_sqft: 2010, exterior_hours: 16, interior_hours: 10 },
  { manufacturer: 'Bombardier', model: 'Challenger 604', category: 'large_jet', seats: 12, wingspan_ft: 64.3, length_ft: 68.4, height_ft: 20.7, surface_area_sqft: 950, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Challenger 605', category: 'large_jet', seats: 12, wingspan_ft: 64.3, length_ft: 68.4, height_ft: 20.7, surface_area_sqft: 955, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Challenger 650', category: 'large_jet', seats: 12, wingspan_ft: 64.3, length_ft: 68.4, height_ft: 20.7, surface_area_sqft: 960, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Bombardier', model: 'Global 5000', category: 'large_jet', seats: 16, wingspan_ft: 94, length_ft: 96.8, height_ft: 24.8, surface_area_sqft: 1600, exterior_hours: 12, interior_hours: 8 },
  { manufacturer: 'Bombardier', model: 'Global 5500', category: 'large_jet', seats: 16, wingspan_ft: 94, length_ft: 96.8, height_ft: 24.8, surface_area_sqft: 1620, exterior_hours: 12, interior_hours: 8 },
  { manufacturer: 'Bombardier', model: 'Global 6000', category: 'large_jet', seats: 17, wingspan_ft: 94, length_ft: 99.4, height_ft: 24.8, surface_area_sqft: 1680, exterior_hours: 12.5, interior_hours: 8.5 },
  { manufacturer: 'Bombardier', model: 'Global 6500', category: 'large_jet', seats: 17, wingspan_ft: 94, length_ft: 99.4, height_ft: 24.8, surface_area_sqft: 1700, exterior_hours: 12.5, interior_hours: 8.5 },
  { manufacturer: 'Bombardier', model: 'Global 7500', category: 'large_jet', seats: 19, wingspan_ft: 104, length_ft: 111, height_ft: 27.5, surface_area_sqft: 2100, exterior_hours: 16, interior_hours: 10 },
  { manufacturer: 'Bombardier', model: 'Global 8000', category: 'large_jet', seats: 19, wingspan_ft: 104, length_ft: 111, height_ft: 27.5, surface_area_sqft: 2120, exterior_hours: 16, interior_hours: 10 },
  { manufacturer: 'Dassault', model: 'Falcon 900', category: 'large_jet', seats: 14, wingspan_ft: 63.4, length_ft: 66.3, height_ft: 24.8, surface_area_sqft: 920, exterior_hours: 7, interior_hours: 5 },
  { manufacturer: 'Dassault', model: 'Falcon 900EX', category: 'large_jet', seats: 14, wingspan_ft: 63.4, length_ft: 66.3, height_ft: 24.8, surface_area_sqft: 930, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Dassault', model: 'Falcon 900LX', category: 'large_jet', seats: 14, wingspan_ft: 70.2, length_ft: 66.3, height_ft: 24.8, surface_area_sqft: 960, exterior_hours: 7.5, interior_hours: 5 },
  { manufacturer: 'Dassault', model: 'Falcon 7X', category: 'large_jet', seats: 16, wingspan_ft: 86, length_ft: 76.1, height_ft: 25.7, surface_area_sqft: 1300, exterior_hours: 10, interior_hours: 7 },
  { manufacturer: 'Dassault', model: 'Falcon 8X', category: 'large_jet', seats: 16, wingspan_ft: 86.3, length_ft: 80.3, height_ft: 25.7, surface_area_sqft: 1380, exterior_hours: 10, interior_hours: 7 },
  { manufacturer: 'Dassault', model: 'Falcon 6X', category: 'large_jet', seats: 16, wingspan_ft: 84.3, length_ft: 77.7, height_ft: 24.1, surface_area_sqft: 1320, exterior_hours: 10, interior_hours: 7 },
  { manufacturer: 'Dassault', model: 'Falcon 10X', category: 'large_jet', seats: 16, wingspan_ft: 101.4, length_ft: 107.6, height_ft: 28.2, surface_area_sqft: 2000, exterior_hours: 15, interior_hours: 10 },
  { manufacturer: 'Embraer', model: 'Legacy 600', category: 'large_jet', seats: 13, wingspan_ft: 69.4, length_ft: 86.4, height_ft: 22.1, surface_area_sqft: 1100, exterior_hours: 8, interior_hours: 6 },
  { manufacturer: 'Embraer', model: 'Legacy 650', category: 'large_jet', seats: 14, wingspan_ft: 69.4, length_ft: 86.4, height_ft: 22.1, surface_area_sqft: 1120, exterior_hours: 8, interior_hours: 6 },
  { manufacturer: 'Embraer', model: 'Lineage 1000E', category: 'large_jet', seats: 19, wingspan_ft: 94.2, length_ft: 118.9, height_ft: 34.6, surface_area_sqft: 2200, exterior_hours: 16, interior_hours: 12 },
  { manufacturer: 'Boeing', model: 'BBJ 737', category: 'large_jet', seats: 25, wingspan_ft: 117.4, length_ft: 138.2, height_ft: 41.2, surface_area_sqft: 3200, exterior_hours: 24, interior_hours: 16 },
  { manufacturer: 'Boeing', model: 'BBJ 737 MAX', category: 'large_jet', seats: 25, wingspan_ft: 117.8, length_ft: 143, height_ft: 40.3, surface_area_sqft: 3300, exterior_hours: 24, interior_hours: 16 },
  { manufacturer: 'Boeing', model: 'BBJ 787', category: 'large_jet', seats: 30, wingspan_ft: 197.2, length_ft: 186.1, height_ft: 55.6, surface_area_sqft: 5500, exterior_hours: 40, interior_hours: 24 },
  { manufacturer: 'Airbus', model: 'ACJ319neo', category: 'large_jet', seats: 25, wingspan_ft: 117.4, length_ft: 111.9, height_ft: 38.6, surface_area_sqft: 2800, exterior_hours: 20, interior_hours: 14 },
  { manufacturer: 'Airbus', model: 'ACJ320neo', category: 'large_jet', seats: 25, wingspan_ft: 117.4, length_ft: 123.3, height_ft: 38.6, surface_area_sqft: 3000, exterior_hours: 22, interior_hours: 15 },
  { manufacturer: 'Airbus', model: 'ACJ330neo', category: 'large_jet', seats: 30, wingspan_ft: 209.9, length_ft: 208.9, height_ft: 56.6, surface_area_sqft: 5800, exterior_hours: 40, interior_hours: 24 },
  { manufacturer: 'Airbus', model: 'ACJ TwoTwenty', category: 'large_jet', seats: 18, wingspan_ft: 115.1, length_ft: 108.9, height_ft: 38.6, surface_area_sqft: 2600, exterior_hours: 18, interior_hours: 12 },

  // ============ HELICOPTERS ============
  { manufacturer: 'Robinson', model: 'R22', category: 'helicopter', seats: 2, wingspan_ft: 25.2, length_ft: 28.8, height_ft: 8.9, surface_area_sqft: 100, exterior_hours: 1.25, interior_hours: 0.5 },
  { manufacturer: 'Robinson', model: 'R44 Raven', category: 'helicopter', seats: 4, wingspan_ft: 33, length_ft: 38.3, height_ft: 10.8, surface_area_sqft: 150, exterior_hours: 1.75, interior_hours: 0.75 },
  { manufacturer: 'Robinson', model: 'R44 Cadet', category: 'helicopter', seats: 2, wingspan_ft: 33, length_ft: 38.3, height_ft: 10.8, surface_area_sqft: 145, exterior_hours: 1.75, interior_hours: 0.75 },
  { manufacturer: 'Robinson', model: 'R66', category: 'helicopter', seats: 5, wingspan_ft: 33.4, length_ft: 39, height_ft: 11.6, surface_area_sqft: 170, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Bell', model: '206 JetRanger', category: 'helicopter', seats: 5, wingspan_ft: 33.4, length_ft: 39.1, height_ft: 9.5, surface_area_sqft: 175, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Bell', model: '206L LongRanger', category: 'helicopter', seats: 7, wingspan_ft: 37, length_ft: 42.5, height_ft: 10.5, surface_area_sqft: 210, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Bell', model: '407', category: 'helicopter', seats: 7, wingspan_ft: 35, length_ft: 41.7, height_ft: 12.6, surface_area_sqft: 200, exterior_hours: 2.25, interior_hours: 1.25 },
  { manufacturer: 'Bell', model: '407GXi', category: 'helicopter', seats: 7, wingspan_ft: 35, length_ft: 41.7, height_ft: 12.6, surface_area_sqft: 205, exterior_hours: 2.25, interior_hours: 1.25 },
  { manufacturer: 'Bell', model: '412', category: 'helicopter', seats: 15, wingspan_ft: 46, length_ft: 56.2, height_ft: 15, surface_area_sqft: 350, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Bell', model: '429', category: 'helicopter', seats: 8, wingspan_ft: 36.1, length_ft: 44.1, height_ft: 13.5, surface_area_sqft: 240, exterior_hours: 2.75, interior_hours: 1.5 },
  { manufacturer: 'Bell', model: '505 Jet Ranger X', category: 'helicopter', seats: 5, wingspan_ft: 34.4, length_ft: 38.1, height_ft: 10.5, surface_area_sqft: 175, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Bell', model: '525 Relentless', category: 'helicopter', seats: 16, wingspan_ft: 52, length_ft: 62, height_ft: 17, surface_area_sqft: 420, exterior_hours: 4, interior_hours: 2.5 },
  { manufacturer: 'Airbus Helicopters', model: 'H120 (EC120)', category: 'helicopter', seats: 5, wingspan_ft: 33.5, length_ft: 38.3, height_ft: 11.1, surface_area_sqft: 170, exterior_hours: 2, interior_hours: 1 },
  { manufacturer: 'Airbus Helicopters', model: 'H125 (AS350)', category: 'helicopter', seats: 6, wingspan_ft: 35.1, length_ft: 42.9, height_ft: 10.8, surface_area_sqft: 195, exterior_hours: 2.25, interior_hours: 1 },
  { manufacturer: 'Airbus Helicopters', model: 'H130 (EC130)', category: 'helicopter', seats: 7, wingspan_ft: 35.1, length_ft: 42.9, height_ft: 11.1, surface_area_sqft: 200, exterior_hours: 2.25, interior_hours: 1.25 },
  { manufacturer: 'Airbus Helicopters', model: 'H135', category: 'helicopter', seats: 8, wingspan_ft: 33.5, length_ft: 39.1, height_ft: 12.7, surface_area_sqft: 210, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Airbus Helicopters', model: 'H145', category: 'helicopter', seats: 10, wingspan_ft: 36.1, length_ft: 43.5, height_ft: 13.1, surface_area_sqft: 240, exterior_hours: 2.75, interior_hours: 1.5 },
  { manufacturer: 'Airbus Helicopters', model: 'H155 (EC155)', category: 'helicopter', seats: 13, wingspan_ft: 42.4, length_ft: 46.3, height_ft: 14.3, surface_area_sqft: 300, exterior_hours: 3.25, interior_hours: 2 },
  { manufacturer: 'Airbus Helicopters', model: 'H160', category: 'helicopter', seats: 12, wingspan_ft: 43.6, length_ft: 49.5, height_ft: 14.8, surface_area_sqft: 310, exterior_hours: 3.25, interior_hours: 2 },
  { manufacturer: 'Airbus Helicopters', model: 'H175', category: 'helicopter', seats: 16, wingspan_ft: 48.6, length_ft: 55.5, height_ft: 16.4, surface_area_sqft: 380, exterior_hours: 3.75, interior_hours: 2.5 },
  { manufacturer: 'Airbus Helicopters', model: 'H215 (AS332)', category: 'helicopter', seats: 19, wingspan_ft: 53.1, length_ft: 63.4, height_ft: 16.1, surface_area_sqft: 450, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Airbus Helicopters', model: 'H225 (EC225)', category: 'helicopter', seats: 19, wingspan_ft: 53.1, length_ft: 63.7, height_ft: 16.4, surface_area_sqft: 460, exterior_hours: 4.5, interior_hours: 3 },
  { manufacturer: 'Leonardo', model: 'AW109 Trekker', category: 'helicopter', seats: 7, wingspan_ft: 36.1, length_ft: 42.6, height_ft: 11.5, surface_area_sqft: 220, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Leonardo', model: 'AW109 GrandNew', category: 'helicopter', seats: 7, wingspan_ft: 36.1, length_ft: 42.6, height_ft: 11.5, surface_area_sqft: 225, exterior_hours: 2.5, interior_hours: 1.25 },
  { manufacturer: 'Leonardo', model: 'AW139', category: 'helicopter', seats: 15, wingspan_ft: 45.3, length_ft: 54.7, height_ft: 16.1, surface_area_sqft: 380, exterior_hours: 3.75, interior_hours: 2.5 },
  { manufacturer: 'Leonardo', model: 'AW169', category: 'helicopter', seats: 10, wingspan_ft: 40.4, length_ft: 46.3, height_ft: 14.1, surface_area_sqft: 270, exterior_hours: 3, interior_hours: 1.75 },
  { manufacturer: 'Leonardo', model: 'AW189', category: 'helicopter', seats: 19, wingspan_ft: 48.9, length_ft: 57.4, height_ft: 17.4, surface_area_sqft: 420, exterior_hours: 4, interior_hours: 2.75 },
  { manufacturer: 'Sikorsky', model: 'S-76D', category: 'helicopter', seats: 12, wingspan_ft: 44, length_ft: 52.5, height_ft: 14.6, surface_area_sqft: 350, exterior_hours: 3.5, interior_hours: 2.25 },
  { manufacturer: 'Sikorsky', model: 'S-92', category: 'helicopter', seats: 19, wingspan_ft: 56.3, length_ft: 64.5, height_ft: 21, surface_area_sqft: 500, exterior_hours: 5, interior_hours: 3.5 },
  { manufacturer: 'MD Helicopters', model: 'MD 500E', category: 'helicopter', seats: 5, wingspan_ft: 26.4, length_ft: 30.5, height_ft: 8.9, surface_area_sqft: 130, exterior_hours: 1.5, interior_hours: 0.75 },
  { manufacturer: 'MD Helicopters', model: 'MD 530F', category: 'helicopter', seats: 5, wingspan_ft: 26.4, length_ft: 32.3, height_ft: 9.4, surface_area_sqft: 140, exterior_hours: 1.5, interior_hours: 0.75 },
  { manufacturer: 'MD Helicopters', model: 'MD 902 Explorer', category: 'helicopter', seats: 8, wingspan_ft: 33.8, length_ft: 38.3, height_ft: 12.1, surface_area_sqft: 200, exterior_hours: 2.25, interior_hours: 1.25 },

  // ============ MILITARY AIRCRAFT ============
  { manufacturer: 'Lockheed Martin', model: 'C-130 Hercules', category: 'turboprop', seats: 92, wingspan_ft: 132.6, length_ft: 97.8, height_ft: 38.3, surface_area_sqft: 2800, exterior_hours: 20, interior_hours: 12 },
  { manufacturer: 'Lockheed Martin', model: 'C-130J Super Hercules', category: 'turboprop', seats: 92, wingspan_ft: 132.6, length_ft: 97.8, height_ft: 38.3, surface_area_sqft: 2850, exterior_hours: 20, interior_hours: 12 },
  { manufacturer: 'Lockheed Martin', model: 'C-5M Super Galaxy', category: 'large_jet', seats: 73, wingspan_ft: 222.7, length_ft: 247.1, height_ft: 65.1, surface_area_sqft: 8000, exterior_hours: 60, interior_hours: 30 },
  { manufacturer: 'Lockheed Martin', model: 'F-16 Fighting Falcon', category: 'light_jet', seats: 2, wingspan_ft: 32.8, length_ft: 49.4, height_ft: 16.7, surface_area_sqft: 450, exterior_hours: 6, interior_hours: 1.5 },
  { manufacturer: 'Lockheed Martin', model: 'F-22 Raptor', category: 'large_jet', seats: 1, wingspan_ft: 44.5, length_ft: 62, height_ft: 16.7, surface_area_sqft: 650, exterior_hours: 8, interior_hours: 1.5 },
  { manufacturer: 'Lockheed Martin', model: 'F-35A Lightning II', category: 'large_jet', seats: 1, wingspan_ft: 35, length_ft: 51.4, height_ft: 14.4, surface_area_sqft: 550, exterior_hours: 7, interior_hours: 1.5 },
  { manufacturer: 'Lockheed Martin', model: 'P-3 Orion', category: 'turboprop', seats: 21, wingspan_ft: 99.7, length_ft: 116.8, height_ft: 33.7, surface_area_sqft: 2400, exterior_hours: 16, interior_hours: 10 },
  { manufacturer: 'Boeing', model: 'F/A-18 Super Hornet', category: 'large_jet', seats: 2, wingspan_ft: 44.9, length_ft: 60.3, height_ft: 16, surface_area_sqft: 600, exterior_hours: 7, interior_hours: 1.5 },
  { manufacturer: 'Boeing', model: 'C-17 Globemaster III', category: 'large_jet', seats: 102, wingspan_ft: 169.8, length_ft: 174, height_ft: 55.1, surface_area_sqft: 5500, exterior_hours: 40, interior_hours: 20 },
  { manufacturer: 'Boeing', model: 'KC-135 Stratotanker', category: 'large_jet', seats: 80, wingspan_ft: 130.8, length_ft: 136.2, height_ft: 41.7, surface_area_sqft: 3600, exterior_hours: 24, interior_hours: 14 },
  { manufacturer: 'Boeing', model: 'KC-46 Pegasus', category: 'large_jet', seats: 64, wingspan_ft: 156.1, length_ft: 165.5, height_ft: 52.2, surface_area_sqft: 4200, exterior_hours: 30, interior_hours: 16 },
  { manufacturer: 'Boeing', model: 'E-3 Sentry (AWACS)', category: 'large_jet', seats: 30, wingspan_ft: 145.8, length_ft: 152.9, height_ft: 41.8, surface_area_sqft: 4000, exterior_hours: 30, interior_hours: 16 },
  { manufacturer: 'Boeing', model: 'P-8 Poseidon', category: 'large_jet', seats: 9, wingspan_ft: 123.6, length_ft: 129.5, height_ft: 42.5, surface_area_sqft: 3200, exterior_hours: 24, interior_hours: 12 },
  { manufacturer: 'Boeing', model: 'AH-64 Apache', category: 'helicopter', seats: 2, wingspan_ft: 48, length_ft: 58.2, height_ft: 15.3, surface_area_sqft: 350, exterior_hours: 4.5, interior_hours: 1.5 },
  { manufacturer: 'Boeing', model: 'CH-47 Chinook', category: 'helicopter', seats: 33, wingspan_ft: 60, length_ft: 98.9, height_ft: 18.8, surface_area_sqft: 700, exterior_hours: 7, interior_hours: 4 },
  { manufacturer: 'Northrop Grumman', model: 'E-2 Hawkeye', category: 'turboprop', seats: 5, wingspan_ft: 80.6, length_ft: 57.6, height_ft: 18.3, surface_area_sqft: 1100, exterior_hours: 8, interior_hours: 3 },
  { manufacturer: 'Northrop Grumman', model: 'B-2 Spirit', category: 'large_jet', seats: 2, wingspan_ft: 172, length_ft: 69, height_ft: 17, surface_area_sqft: 3500, exterior_hours: 30, interior_hours: 3 },
  { manufacturer: 'Northrop Grumman', model: 'C-2 Greyhound', category: 'turboprop', seats: 26, wingspan_ft: 80.6, length_ft: 56.8, height_ft: 15.9, surface_area_sqft: 1050, exterior_hours: 8, interior_hours: 4 },
  { manufacturer: 'General Dynamics', model: 'F-111 Aardvark', category: 'large_jet', seats: 2, wingspan_ft: 63, length_ft: 73.5, height_ft: 17.1, surface_area_sqft: 800, exterior_hours: 8, interior_hours: 2 },
  { manufacturer: 'Bell', model: 'UH-1 Huey', category: 'helicopter', seats: 14, wingspan_ft: 48, length_ft: 57.1, height_ft: 14.7, surface_area_sqft: 320, exterior_hours: 3.5, interior_hours: 2 },
  { manufacturer: 'Bell', model: 'AH-1Z Viper', category: 'helicopter', seats: 2, wingspan_ft: 48, length_ft: 58.3, height_ft: 14.2, surface_area_sqft: 310, exterior_hours: 4, interior_hours: 1.25 },
  { manufacturer: 'Bell', model: 'V-22 Osprey', category: 'helicopter', seats: 24, wingspan_ft: 84.6, length_ft: 57.3, height_ft: 22.1, surface_area_sqft: 800, exterior_hours: 8, interior_hours: 4 },
  { manufacturer: 'Sikorsky', model: 'UH-60 Black Hawk', category: 'helicopter', seats: 14, wingspan_ft: 53.7, length_ft: 64.8, height_ft: 16.8, surface_area_sqft: 420, exterior_hours: 4.5, interior_hours: 2.5 },
  { manufacturer: 'Sikorsky', model: 'CH-53E Super Stallion', category: 'helicopter', seats: 37, wingspan_ft: 79, length_ft: 99.1, height_ft: 28.3, surface_area_sqft: 850, exterior_hours: 8, interior_hours: 5 },
  { manufacturer: 'Sikorsky', model: 'MH-60 Seahawk', category: 'helicopter', seats: 14, wingspan_ft: 53.7, length_ft: 64.8, height_ft: 16.8, surface_area_sqft: 420, exterior_hours: 4.5, interior_hours: 2.5 },
  { manufacturer: 'Sikorsky', model: 'VH-92 Patriot', category: 'helicopter', seats: 14, wingspan_ft: 56.3, length_ft: 64.5, height_ft: 21, surface_area_sqft: 500, exterior_hours: 5, interior_hours: 3 },
  { manufacturer: 'Textron Aviation', model: 'T-6 Texan II', category: 'turboprop', seats: 2, wingspan_ft: 33.4, length_ft: 33.3, height_ft: 10.7, surface_area_sqft: 280, exterior_hours: 3, interior_hours: 1 },
  { manufacturer: 'BAE Systems', model: 'Hawk T2', category: 'light_jet', seats: 2, wingspan_ft: 30.8, length_ft: 39.8, height_ft: 13.1, surface_area_sqft: 320, exterior_hours: 3.5, interior_hours: 1 },
  { manufacturer: 'Fairchild Republic', model: 'A-10 Thunderbolt II', category: 'large_jet', seats: 1, wingspan_ft: 57.5, length_ft: 53.3, height_ft: 14.7, surface_area_sqft: 700, exterior_hours: 8, interior_hours: 1.5 },
  { manufacturer: 'Grumman', model: 'E-2C Hawkeye', category: 'turboprop', seats: 5, wingspan_ft: 80.6, length_ft: 57.6, height_ft: 18.3, surface_area_sqft: 1100, exterior_hours: 8, interior_hours: 3 },
  { manufacturer: 'McDonnell Douglas', model: 'F-15 Eagle', category: 'large_jet', seats: 2, wingspan_ft: 42.8, length_ft: 63.7, height_ft: 18.5, surface_area_sqft: 650, exterior_hours: 7, interior_hours: 1.5 },
  { manufacturer: 'McDonnell Douglas', model: 'AV-8B Harrier II', category: 'light_jet', seats: 1, wingspan_ft: 30.3, length_ft: 46.3, height_ft: 11.6, surface_area_sqft: 380, exterior_hours: 5, interior_hours: 1 },
  { manufacturer: 'Rockwell Collins', model: 'B-1B Lancer', category: 'large_jet', seats: 4, wingspan_ft: 137, length_ft: 146, height_ft: 34, surface_area_sqft: 3200, exterior_hours: 24, interior_hours: 6 },
  { manufacturer: 'Boeing', model: 'B-52 Stratofortress', category: 'large_jet', seats: 5, wingspan_ft: 185, length_ft: 159.3, height_ft: 40.7, surface_area_sqft: 4500, exterior_hours: 32, interior_hours: 8 },
  { manufacturer: 'Boeing', model: 'V-22 Osprey', category: 'helicopter', seats: 24, wingspan_ft: 84.6, length_ft: 57.3, height_ft: 22.1, surface_area_sqft: 800, exterior_hours: 8, interior_hours: 4 },
];
