ALTER TABLE detailers ADD COLUMN IF NOT EXISTS availability JSONB DEFAULT NULL;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS time_preference TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS scheduling_notes TEXT;
